2014-06-30 00:53:33-0400 [-] Log opened.
2014-06-30 00:53:33-0400 [PyHouse.CoreSetup   ] 
	------------------------------------------------------------------
	
	
2014-06-30 00:53:33-0400 [PyHouse.Computer    ] Starting
2014-06-30 00:53:33-0400 [PyHouse.NodeDiscovry] Initialized.
2014-06-30 00:53:33-0400 [PyHouse.WebServer   ] Initialized.
	
2014-06-30 00:53:33-0400 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 416, in fireEvent
	    DeferredList(beforeResults).addCallback(self._continueFiring)
	  File "/usr/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 306, in addCallback
	    callbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "/usr/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/briank/workspace/PyHouse/src/PyHouse.py", line 172, in Start
	    self.m_pyhouse_obj.APIs.CoreAPI.Start(self.m_pyhouse_obj)
	  File "/home/briank/workspace/PyHouse/src/Modules/Core/setup.py", line 97, in Start
	    p_pyhouse_obj.APIs.ComputerAPI.Start(p_pyhouse_obj)  # Logs now started
	  File "/home/briank/workspace/PyHouse/src/Modules/Comps/computer.py", line 70, in Start
	    p_pyhouse_obj.APIs.InternetAPI.Start(p_pyhouse_obj)
	  File "/home/briank/workspace/PyHouse/src/Modules/Comps/internet.py", line 365, in Start
	    l_internet_xml = self.find_xml(p_pyhouse_obj)
	  File "/home/briank/workspace/PyHouse/src/Modules/Comps/internet.py", line 342, in find_xml
	    l_ret = l_ret.find('InternetSection')
	exceptions.AttributeError: 'NoneType' object has no attribute 'find'
	
2014-06-30 00:53:48-0400 [-] Received SIGTERM, shutting down.
2014-06-30 00:53:48-0400 [-] Main loop terminated.
2014-06-30 00:53:48-0400 [PyHouse             ] PyHouse says Bye Now.
	
2014-06-30 00:53:48-0400 [-] PyHouse says Bye Now.
2014-06-30 00:54:53-0400 [-] Log opened.
2014-06-30 00:54:53-0400 [PyHouse.CoreSetup   ] 
	------------------------------------------------------------------
	
	
2014-06-30 00:54:53-0400 [PyHouse.Computer    ] Starting
2014-06-30 00:54:53-0400 [PyHouse.NodeDiscovry] Initialized.
2014-06-30 00:54:53-0400 [PyHouse.WebServer   ] Initialized.
	
2014-06-30 00:54:53-0400 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 416, in fireEvent
	    DeferredList(beforeResults).addCallback(self._continueFiring)
	  File "/usr/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 306, in addCallback
	    callbackKeywords=kw)
	  File "/usr/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "/usr/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/briank/workspace/PyHouse/src/PyHouse.py", line 172, in Start
	    self.m_pyhouse_obj.APIs.CoreAPI.Start(self.m_pyhouse_obj)
	  File "/home/briank/workspace/PyHouse/src/Modules/Core/setup.py", line 97, in Start
	    p_pyhouse_obj.APIs.ComputerAPI.Start(p_pyhouse_obj)  # Logs now started
	  File "/home/briank/workspace/PyHouse/src/Modules/Comps/computer.py", line 70, in Start
	    p_pyhouse_obj.APIs.InternetAPI.Start(p_pyhouse_obj)
	  File "/home/briank/workspace/PyHouse/src/Modules/Comps/internet.py", line 365, in Start
	    l_internet_xml = self.find_xml(p_pyhouse_obj)
	  File "/home/briank/workspace/PyHouse/src/Modules/Comps/internet.py", line 342, in find_xml
	    l_ret = l_ret.find('InternetSection')
	exceptions.AttributeError: 'NoneType' object has no attribute 'find'
	
2014-06-30 00:55:07-0400 [-] Received SIGTERM, shutting down.
2014-06-30 00:55:07-0400 [-] Main loop terminated.
2014-06-30 00:55:07-0400 [PyHouse             ] PyHouse says Bye Now.
	
2014-06-30 00:55:07-0400 [-] PyHouse says Bye Now.
