2014-06-27 17:09:18-0400 [-] Log opened.
2014-06-27 17:09:18-0400 [PyHouse.CoreSetup   ] 
	------------------------------------------------------------------
	
	
2014-06-27 17:09:18-0400 [PyHouse.Computer    ] Starting
2014-06-27 17:09:18-0400 [PyHouse.WebServer   ] Initialized.
	
2014-06-27 17:09:18-0400 [-] Unhandled Error
	Traceback (most recent call last):
	  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 416, in fireEvent
	    DeferredList(beforeResults).addCallback(self._continueFiring)
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 306, in addCallback
	    callbackKeywords=kw)
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\PyHouse.py", line 172, in Start
	    self.m_pyhouse_obj.APIs.CoreAPI.Start(self.m_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Core\setup.py", line 104, in Start
	    p_pyhouse_obj.APIs.ComputerAPI.Start(p_pyhouse_obj)  # Logs now started
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\computer.py", line 70, in Start
	    p_pyhouse_obj.APIs.InternetAPI.Start(p_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\internet.py", line 365, in Start
	    l_internet_xml = self.find_xml(p_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\internet.py", line 342, in find_xml
	    l_ret = l_ret.find('InternetSection')
	exceptions.AttributeError: 'NoneType' object has no attribute 'find'
	
2014-06-27 17:10:21-0400 [-] Log opened.
2014-06-27 17:10:21-0400 [PyHouse.CoreSetup   ] 
	------------------------------------------------------------------
	
	
2014-06-27 17:10:21-0400 [PyHouse.Computer    ] Starting
2014-06-27 17:10:21-0400 [PyHouse.WebServer   ] Initialized.
	
2014-06-27 17:10:21-0400 [-] Unhandled Error
	Traceback (most recent call last):
	  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 416, in fireEvent
	    DeferredList(beforeResults).addCallback(self._continueFiring)
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 306, in addCallback
	    callbackKeywords=kw)
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\PyHouse.py", line 172, in Start
	    self.m_pyhouse_obj.APIs.CoreAPI.Start(self.m_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Core\setup.py", line 104, in Start
	    p_pyhouse_obj.APIs.ComputerAPI.Start(p_pyhouse_obj)  # Logs now started
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\computer.py", line 70, in Start
	    p_pyhouse_obj.APIs.InternetAPI.Start(p_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\internet.py", line 365, in Start
	    l_internet_xml = self.find_xml(p_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\internet.py", line 342, in find_xml
	    l_ret = l_ret.find('InternetSection')
	exceptions.AttributeError: 'NoneType' object has no attribute 'find'
	
2014-06-27 21:07:25-0400 [-] Log opened.
2014-06-27 21:07:25-0400 [PyHouse.CoreSetup   ] 
	------------------------------------------------------------------
	
	
2014-06-27 21:07:25-0400 [PyHouse.Computer    ] Starting
2014-06-27 21:07:25-0400 [PyHouse.WebServer   ] Initialized.
	
2014-06-27 21:07:25-0400 [-] Unhandled Error
	Traceback (most recent call last):
	  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 416, in fireEvent
	    DeferredList(beforeResults).addCallback(self._continueFiring)
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 306, in addCallback
	    callbackKeywords=kw)
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\PyHouse.py", line 172, in Start
	    self.m_pyhouse_obj.APIs.CoreAPI.Start(self.m_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Core\setup.py", line 104, in Start
	    p_pyhouse_obj.APIs.ComputerAPI.Start(p_pyhouse_obj)  # Logs now started
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\computer.py", line 70, in Start
	    p_pyhouse_obj.APIs.InternetAPI.Start(p_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\internet.py", line 365, in Start
	    l_internet_xml = self.find_xml(p_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\internet.py", line 342, in find_xml
	    l_ret = l_ret.find('InternetSection')
	exceptions.AttributeError: 'NoneType' object has no attribute 'find'
	
2014-06-27 21:08:06-0400 [-] Log opened.
2014-06-27 21:08:06-0400 [PyHouse.CoreSetup   ] 
	------------------------------------------------------------------
	
	
2014-06-27 21:08:06-0400 [PyHouse.Computer    ] Starting
2014-06-27 21:08:06-0400 [PyHouse.WebServer   ] Initialized.
	
2014-06-27 21:08:06-0400 [-] Unhandled Error
	Traceback (most recent call last):
	  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 416, in fireEvent
	    DeferredList(beforeResults).addCallback(self._continueFiring)
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 306, in addCallback
	    callbackKeywords=kw)
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\PyHouse.py", line 172, in Start
	    self.m_pyhouse_obj.APIs.CoreAPI.Start(self.m_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Core\setup.py", line 104, in Start
	    p_pyhouse_obj.APIs.ComputerAPI.Start(p_pyhouse_obj)  # Logs now started
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\computer.py", line 70, in Start
	    p_pyhouse_obj.APIs.InternetAPI.Start(p_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\internet.py", line 365, in Start
	    l_internet_xml = self.find_xml(p_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\internet.py", line 342, in find_xml
	    l_ret = l_ret.find('InternetSection')
	exceptions.AttributeError: 'NoneType' object has no attribute 'find'
	
2014-06-27 21:11:32-0400 [-] Log opened.
2014-06-27 21:11:32-0400 [PyHouse.CoreSetup   ] 
	------------------------------------------------------------------
	
	
2014-06-27 21:11:32-0400 [PyHouse.Computer    ] Starting
2014-06-27 21:11:32-0400 [PyHouse.WebServer   ] Initialized.
	
2014-06-27 21:11:32-0400 [-] Unhandled Error
	Traceback (most recent call last):
	  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 416, in fireEvent
	    DeferredList(beforeResults).addCallback(self._continueFiring)
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 306, in addCallback
	    callbackKeywords=kw)
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\PyHouse.py", line 172, in Start
	    self.m_pyhouse_obj.APIs.CoreAPI.Start(self.m_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Core\setup.py", line 104, in Start
	    p_pyhouse_obj.APIs.ComputerAPI.Start(p_pyhouse_obj)  # Logs now started
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\computer.py", line 70, in Start
	    p_pyhouse_obj.APIs.InternetAPI.Start(p_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\internet.py", line 365, in Start
	    l_internet_xml = self.find_xml(p_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\internet.py", line 342, in find_xml
	    l_ret = l_ret.find('InternetSection')
	exceptions.AttributeError: 'NoneType' object has no attribute 'find'
	
2014-06-27 21:12:08-0400 [-] Log opened.
2014-06-27 21:12:08-0400 [PyHouse.CoreSetup   ] 
	------------------------------------------------------------------
	
	
2014-06-27 21:12:08-0400 [PyHouse.Computer    ] Starting
2014-06-27 21:12:08-0400 [PyHouse.WebServer   ] Initialized.
	
2014-06-27 21:12:08-0400 [-] Unhandled Error
	Traceback (most recent call last):
	  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 416, in fireEvent
	    DeferredList(beforeResults).addCallback(self._continueFiring)
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 306, in addCallback
	    callbackKeywords=kw)
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\PyHouse.py", line 172, in Start
	    self.m_pyhouse_obj.APIs.CoreAPI.Start(self.m_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Core\setup.py", line 104, in Start
	    p_pyhouse_obj.APIs.ComputerAPI.Start(p_pyhouse_obj)  # Logs now started
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\computer.py", line 70, in Start
	    p_pyhouse_obj.APIs.InternetAPI.Start(p_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\internet.py", line 365, in Start
	    l_internet_xml = self.find_xml(p_pyhouse_obj)
	  File "C:\Users\briank\Documents\GitHub\PyHouse\src\Modules\Comps\internet.py", line 342, in find_xml
	    l_ret = l_ret.find('InternetSection')
	exceptions.AttributeError: 'NoneType' object has no attribute 'find'
	
